version: '3.2'
services:
  gitserver:
    image: 'local-gitserver-http'
    command:
      - '-init'
      - '-start'
    volumes:
      - './initial:/var/lib/initial:ro'
    ports:
      - '8080:80'
